### ISSUE TITLE
[CI] Fix: Restrict "gofmt" formatting check to Linux in test.yml

### ISSUE THREAD

**Issue by Thedarkmatter10** [civo/civogo#245]
### The` test.yml` workflow includes a step to ensure Go files are properly formatted:

```yaml
- name: Ensure correctly formatted
  run: test -z "$(gofmt -l $(find . -type f -name '*.go'))"
```

This works fine on **Linux**, but fails or behaves **inconsistently** on Windows because it relies on **Unix-style shell commands** like find and test.

Since the test matrix includes windows-latest, this step should only run on Linux.

#### Proposed fix:

```yaml
- name: Ensure correctly formatted
  if: runner.os == 'Linux'
  run: test -z "$(gofmt -l $(find . -type f -name '*.go'))"
```

**Happy to open a pull request if approved!**
@andyjeffries 
@uzaxirr
